### ISSUE TITLE
Unhandled Exception: PlatformException(error, A ContentProvider for this app was not set up in the AndroidManifest.xml, please add com.facebook.app.FacebookContentProvider@strings/facebook_app_id as a provider to your AndroidManifest.xml file. See https://developers.facebook.com/docs/sharing/android for more info., null)

### ISSUE THREAD

**Issue by VeerneToor** [romatroskin/social_share_plugin#14] opened 2020-02-05 14:32 UTC
**Manifest**

`        
        <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@strings/facebook_app_id"/>

        <activity android:name="com.facebook.CustomTabActivity" android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="fb501633813737055" />
            </intent-filter>
        </activity>
        

        
        <activity android:name="com.facebook.FacebookActivity"
            android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:label="@strings/app_name" />

        <provider android:authorities="com.facebook.app.FacebookContentProvider501633813737055"
            android:name="com.facebook.FacebookContentProvider"
            android:exported="false"/>
        `

**Comment by kaarens93** [comment] 2020-02-06 01:20
`<provider android:authorities="com.facebook.app.FacebookContentProvider501633813737055"
        android:name="com.facebook.FacebookContentProvider"
        android:exported="true"/>`
I think android:exported needs to be set to true

**Comment by VeerneToor** [comment] 2020-02-06 03:49
> `<provider android:authorities="com.facebook.app.FacebookContentProvider501633813737055" android:name="com.facebook.FacebookContentProvider" android:exported="true"/>`
> I think android:exported needs to be set to true

Yes, i already try tht, but downt work :C

**Comment by romatroskin** [comment] 2020-02-21 11:41
please show your full manifest

**Comment by VeerneToor** [comment] 2020-02-24 18:22
> please show your full manifest, looks like you have wrong setup

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="co.______________.mi_empresa"
    android:versionCode="2"
    android:versionName="debug_version">
    
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

    <application
        android:name="io.flutter.app.FlutterApplication"
        android:icon="@mipmap/ic_launcher"
        android:label="Mi Empresa"
        android:usesCleartextTraffic="true"
        tools:replace="android:label"
        tools:ignore="GoogleAppIndexingWarning">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>

               
        <activity
            android:name="com.facebook.CustomTabActivity"
            android:exported="true">

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="fb5016___________" />
            </intent-filter>
        </activity>
        


        
        <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@strings/facebook_app_id"/>

        <activity
            android:name="com.facebook.FacebookActivity"
            android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:label="@strings/app_name"/>

        
        <provider
            android:authorities="com.facebook.app.FacebookContentProvider@strings/facebook_app_id"
            android:name="com.facebook.FacebookContentProvider"
            android:exported="true"/>
        

        <provider android:name="androidx.core.content.FileProvider"
            android:authorities="com.solucionescolombia.mi_empresa.social.share.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">

            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>
        



        <receiver
            android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">

            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>

        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />

        <meta-data
            android:name="com.google.android.maps.v2.API_KEY"
            android:value="AIzaSyBwTB____________aaApIO7_______UdGs"/>
    </application>


</manifest>

**Comment by romatroskin** [comment] 2020-03-03 12:46
Duplicate of #13

**Closed by romatroskin** 2020-03-03 12:46 UTC
