### ISSUE TITLE
share To Feed facebook is not working

### ISSUE THREAD

**Issue by alvinjstu** [romatroskin/social_share_plugin#8] opened 2019-11-22 08:17 UTC

**Comment by alvinjstu** [comment] 2019-11-22 08:22
I try to run your example,  share to feed facebook is not working!!
logs:


D/ViewRootImpl@f0cf194[MainActivity](25246): dispatchDetachedFromWindow
D/InputTransport(25246): Input channel destroyed: fd=86
I/System.out(25246): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(25246): (HTTPLog)-Static: isSBSettingEnabled false
E/GraphResponse(25246): {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Some of the aliases you requested do not exist: 000000000000000}
I/System.out(25246): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(25246): (HTTPLog)-Static: isSBSettingEnabled false
E/GraphResponse(25246): {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Some of the aliases you requested do not exist: 000000000000000}
I/System.out(25246): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(25246): (HTTPLog)-Static: isSBSettingEnabled false
E/GraphResponse(25246): {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Some of the aliases you requested do not exist: 000000000000000}
I/System.out(25246): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(25246): (HTTPLog)-Static: isSBSettingEnabled false
E/GraphResponse(25246): {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Some of the aliases you requested do not exist: 000000000000000}
Lost connection to device.

**Comment by romatroskin** [comment] 2020-02-21 11:44
please try with updated version

**Comment by awhitford** [comment] 2020-03-11 20:51
I have a straight forward example:
```dart
                        print("Sharing on Facebook...");
                        await SocialSharePlugin.shareToFeedFacebookLink(
                          quote: 'This is my message',
                          url: 'https://acme.com',
                          onSuccess: (postId) async {
                            return print("Facebook share success: $postId");
                          },
                          onError: (error) async {
                            return print("Facebook share failure: $error");
                          },
                          onCancel: () async {
                            return print("Facebook share canceled!");
                          },
                        );
                        print("Done Sharing on Facebook.");
```

And I see the following output:
```
flutter: Sharing on Facebook...
flutter: Done Sharing on Facebook.
```

**I don't see anything really happening, nor do I see any errors.**  I am using the iOS Simulator.

I am using the latest version: **`social_share_plugin: ^0.3.0+1`**

**Comment by romatroskin** [comment] 2020-03-18 11:33
duplicate of #11

**Closed by romatroskin** 2020-03-18 11:33 UTC

**Comment by DevRahul123** [comment] 2020-05-15 12:10
Hi @romatroskin i am also facing this issue & i am running my app on android device, i am using this version of plugin :: social_share_plugin: ^0.3.1+1

**Comment by romatroskin** [comment] 2020-05-15 12:13
have you configured it right with your Facebook is instead of 0000..0000? take a look at the example and check please

**Comment by DevRahul123** [comment] 2020-05-15 12:26
yes i've configured it properly, the issue is only with the callbacks because the post got successfully shared on my facebook wall, but the success callback never triggers

**Comment by bharathiv985** [comment] 2023-12-11 12:46
I am also facing this issue, success callback alone not working. OnCancel and OnError callback are working fine.
